### ISSUE TITLE
Peer screen flickering on Linux

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync#149] opened 2023-12-22 10:16 UTC
- happen on my Linux when the Linux has a higher protocol version than some other device that it's trying to connect to (could be vice-versa as well, but that I haven't tried).
- Could be because the handshake fails but then the peer is rediscovered and new connection attempt starts.
- Yes, although I think it's not being rediscovered, but there is a timeout. Perhaps we could have another enum (Dht, LocallyDiscovered, ...) that indicates that it's known but will be retried later
- We have this SeenPeers things which I think should handle this. But problem is when the handshake fails, we completely stop the connection attempt and drop the SeenPeer handle which makes the peer immediately available for rediscovery. At least that's how I understand it.
- (conversation on MM, QA channel 21 Dec 2023)
- Assigning to you, @inetic as you are already looking into it

**Comment by inetic** [comment] 2023-12-22 12:52
So the problem seems to be that when two replicas find each other but they don't share a repository (yet), then the timeout and socket close mechanism doesn't seem to work. To reproduce:

* have two devices, say one Linux and the other one Android
* make them have zero repositories
* start both of them and observe as they add each other in the peers table
* kill the Linux replica and observe that it's not removed from the peers table on the Android replica, even after some couple of minutes

**Comment by madadam** [comment] 2023-12-22 13:21
Related #129

**Comment by inetic** [comment] 2023-12-22 13:22
This means we have at least two problems:

1. The timeout mechanism works only on the virtual connections and doesn't work when two replicas don't share a repository
2. When the Android app is closed, the library is likely killed right a way and it doesn't give the QUIC library enough time to send closing packets

Of the two, the #1 is is the mostly important one. The #2 is a nice to have to have the connections closed as soon as possible, but #2 can fail even if implemented correctly, that's why #1 is a must.

**Comment by inetic** [comment] 2024-01-15 10:15
Should be fixed by merge https://github.com/equalitie/ouisync/commit/58747ddea08c417f52f7f4042321888e1040528a

**Closed by inetic** 2024-01-15 10:15 UTC
