### ISSUE TITLE
Removing large files takes a long time to finish

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync#90] opened 2022-11-14 15:08 UTC
Possible solutions:

1. We could create a tombsone with that blob as optional data. This way the user would no longer see the file and block removal could be happening in the background.
2. We could create a tombsone without any additional data (as we have now), start deleting the blob and if the app terminates in the mean time we leave it to the garbage collector to remove the orphaned blocks.
3. We do nothing apart from maybe adding a progress bar in the app indicating that deletion is taking place.

**Comment by madadam** [comment] 2022-11-22 14:29
Related to (possibly duplicate of) #67

**Closed** 2022-12-15 13:28 UTC
